-keep class com.google.android.exoplayer2.** { *; }
-keep interface com.google.android.exoplayer2.** { *; }
-keep class retrofit2.** { *; }
-keep interface retrofit2.** { *; }
-keep class com.google.gson.** { *; }
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer
-keep class androidx.room.** { *; }
-keep class * extends androidx.room.RoomDatabase
-keep class com.ultrastream.data.models.** { *; }
-keep class * implements android.os.Parcelable { public static final *** CREATOR; }
-keep class * implements java.io.Serializable
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keepattributes Signature
-keep class androidx.core.content.FileProvider { *; }
-keep class com.google.android.exoplayer2.ext.** { *; }
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
